Agregado acortador de titulo y mergen de tools
chamilo/mobile-messaging pull request #11
Opened 2016-11-22 22:49 UTC by aragonc

2016-11-23 14:45 UTC, AngelFQC requested changes
También prueba home de al app con sesiones y categorías de sesiones :smile:

2016-11-23 14:45 UTC, AngelFQC commented on www/src/template/course-forumthread.html
> +            <a class="navbar-brand title" id="btn-reply" href="#" role="button" title="Reply" data-toggle="modal" data-target="#dlg-reply">
Ese es sólo un botón, no tiene mas texto que el ícono. No debería tener la clase ```title```
En pantallas un poco pequeñas, se ve así
Vertical ![vertical](https://cloud.githubusercontent.com/assets/1697880/20563653/7e7f4058-b157-11e6-890c-ba25a4468a63.png)
Horizontal ![horizontal](https://cloud.githubusercontent.com/assets/1697880/20563652/7e77b04a-b157-11e6-945d-e7afe7cc5aa8.png)

2016-11-23 14:45 UTC, AngelFQC commented on www/css/app.css
> +    margin-bottom: 5px;
Los márgenes por defecto en Bootstrap son ```15px```

2016-11-23 14:55 UTC, AngelFQC commented
En un tablet podría verse, en algunos casos así...
![tablet](https://cloud.githubusercontent.com/assets/1697880/20566382/e1d488f6-b162-11e6-923c-60a7a2fb7516.png)

2017-05-11 21:41 UTC, AngelFQC commented
Ping @aragonc

2017-05-11 22:05 UTC, aragonc commented
@AngelFQC  que ha pasaoooo ¡¡??

2019-08-15 21:54 UTC, closed without merging